# Generated by Django 4.2.4 on 2023-08-28 21:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mediafiles', '0003_mediafile_metadata_mediafile_thumbnail_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='mediafile',
            name='filetype',
            field=models.CharField(choices=[('image', 'Image'), ('video', 'Video'), ('audio', 'Audio')], default='image', max_length=10),
        ),
    ]
