# Generated by Django 4.2.4 on 2023-08-28 22:18

from django.db import migrations
import taggit.managers


class Migration(migrations.Migration):

    dependencies = [
        ('taggit', '0005_auto_20220424_2025'),
        ('mediafiles', '0004_mediafile_filetype'),
    ]

    operations = [
        migrations.AddField(
            model_name='mediafile',
            name='tags',
            field=taggit.managers.TaggableManager(blank=True, help_text='A comma-separated list of tags.', through='taggit.TaggedItem', to='taggit.Tag', verbose_name='Tags'),
        ),
    ]
